In [5]:
import import_ipynb #allows access to import other notebooks
from PreprocessLib import cleanText, removeSingleLists

importing Jupyter notebook from PreprocessLib.ipynb


In [6]:
import spacy
#processes file for W2V, tokenizes text if tokenize is true, then returns text
def process_file(a_file, tokenize=True):
    string_without_line_breaks = ""
    for line in a_file:
        stripped_line = line.rstrip() + " "
        string_without_line_breaks += stripped_line
    a_file.close()
    sentences = string_without_line_breaks
    
    
   
    if (tokenize == False):
        cleanedFile = cleanText(sentences, tokenize)
        return cleanedFile
    cleanedFile = cleanText(sentences) #cleanText is found in PreprocessLib.ipynb
        
    output_doc = []
    nlp = spacy.load("el_core_news_sm")

    for sentence in cleanedFile:
        temp = []
        doc = nlp(sentence)
        for token in doc:
            temp.append(token.text)
        output_doc.append(temp)
        output_doc = removeSingleLists(output_doc)
    return output_doc

In [7]:
#processes files for Word2Vec
longFile = open("./other-sources/Longus.txt", "r", encoding="utf8")
markFile = open("./other-sources/Mark.txt", "r", encoding="utf8")
mathFile = open("./other-sources/Mathew.txt", "r", encoding="utf8")
ignatFile = open("./other-sources/Ignatius.txt", "r", encoding="utf8")
testFile = open("./other-sources/Ignatius-3books.txt", "r", encoding="utf8")
long = process_file(longFile)
mark = process_file(markFile)
math = process_file(mathFile)
ignat = process_file(ignatFile)
test = process_file(testFile)

#processes files for vocab extraction
longFile = open("./other-sources/Longus.txt", "r", encoding="utf8")
markFile = open("./other-sources/Mark.txt", "r", encoding="utf8")
mathFile = open("./other-sources/Mathew.txt", "r", encoding="utf8")
ignatFile = open("./other-sources/Ignatius-4.txt", "r", encoding="utf8")
testFile = open("./other-sources/Ignatius-3books.txt", "r", encoding="utf8")
longFreq = process_file(longFile, False)
markFreq = process_file(markFile, False)
mathFreq = process_file(mathFile, False)
ignatFreq = process_file(ignatFile, False)
testFreq = process_file(testFile, False)

In [10]:
import gensim
from gensim.models import Word2Vec  

longModel = Word2Vec(min_count = 1, alpha=0.025, sample=0.0001, size=100, sg=1) 
longModel.build_vocab(long)
longModel.train(long, total_examples=longModel.corpus_count, epochs=longModel.iter)

markModel = Word2Vec(min_count = 1, alpha=0.025, sample=0.0001, size=100, sg=1) 
markModel.build_vocab(mark)
markModel.train(mark, total_examples=markModel.corpus_count, epochs=markModel.iter)

mathModel = Word2Vec(min_count = 1, alpha=0.025, sample=0.0001, size=100, sg=1) 
mathModel.build_vocab(math)
mathModel.train(math, total_examples=mathModel.corpus_count, epochs=mathModel.iter)

ignatModel = Word2Vec(min_count = 1, alpha=0.025, sample=0.0001, size=100, sg=1) 
ignatModel.build_vocab(ignat)
ignatModel.train(ignat, total_examples=ignatModel.corpus_count, epochs=ignatModel.iter)

testModel = Word2Vec(min_count = 1, alpha=0.025, sample=0.0001, size=100, sg=1) 
testModel.build_vocab(test)
testModel.train(test, total_examples=testModel.corpus_count, epochs=testModel.iter)


<ipython-input-10-642267fcc224>:6: DeprecationWarning: Call to deprecated `iter` (Attribute will be removed in 4.0.0, use self.epochs instead).
  longModel.train(long, total_examples=longModel.corpus_count, epochs=longModel.iter)
<ipython-input-10-642267fcc224>:10: DeprecationWarning: Call to deprecated `iter` (Attribute will be removed in 4.0.0, use self.epochs instead).
  markModel.train(mark, total_examples=markModel.corpus_count, epochs=markModel.iter)
<ipython-input-10-642267fcc224>:14: DeprecationWarning: Call to deprecated `iter` (Attribute will be removed in 4.0.0, use self.epochs instead).
  mathModel.train(math, total_examples=mathModel.corpus_count, epochs=mathModel.iter)
<ipython-input-10-642267fcc224>:18: DeprecationWarning: Call to deprecated `iter` (Attribute will be removed in 4.0.0, use self.epochs instead).
  ignatModel.train(ignat, total_examples=ignatModel.corpus_count, epochs=ignatModel.iter)
<ipython-input-10-642267fcc224>:22: DeprecationWarning: Call to deprecate

(6846, 15935)

In [11]:
#saving the best models
longModel.save("longModel.model")
markModel.save("markModel.model")
mathModel.save("mathModel.model")
ignatModel.save("ignatModel.model")
testModel.save("testModel.model")

In [13]:
#takes in a W2V model and returns the associated vocabulary of the model
def intoDict (model): 
    # Get the ordered list of words in the vocabulary
    words = model.wv.vocab.keys()
    # Make a dictionary
    we_dict = {word:model.wv[word] for word in words}
    return we_dict

In [14]:
#takes a dictionary "dct", a list of words "wordList", and optionally a label
#takes each word vector of the words in wordList and adds them to an overall vector, then returns this vector
def createVec(dct, wordList, label="NA"):
    vec = []
    for word in wordList:
        vec.append(dct[word])
    if (label != "NA"):
        vec.append(label)
    return vec

In [8]:
#returns all similar words of the texts
def getAllSimWords():
    simWords = []
    for word in testDict:
        puncuation = [",", "."]
        if (word in longDict and word in markDict and word in mathDict and word in ignatDict and word not in puncuation):
            simWords.append(word)
    return simWords

In [20]:
#creating vocab dictionaries of the models
longDict = intoDict(longModel)
markDict = intoDict(markModel)
mathDict = intoDict(mathModel)
ignatDict = intoDict(ignatModel)
testDict = intoDict(testModel)


#commonWordList = ['πάντα', 'αὐτοῦ', 'ἐστιν', 'με', 'αὐτὸν', 'αὐτῶν', 'τοῦτο', 'ἵνα']
#commonWordList = ['καὶ', 'ἐν', 'τοῦ', 'τὸ', 'εἰς', 'δὲ', 'ὁ', 'μὴ', 'αὐτοῦ', 'γὰρ', 'τῇ', 'ὡς', 'τὰ', 'τῶν', 'τὸν'
#                , 'ἡ', 'τῆς', 'οὐ', 'τὴν', 'διὰ', 'πάντα', 'οὐκ', 'τοῖς', 'ὅτι', 'ἀλλὰ', 'τοὺς', 'με', 'ἵνα']
commonWordList = getAllSimWords()
#creating vectors to represent the models based on the commonWordList
longVec = createVec(longDict, commonWordList, 'Longus')
markVec = createVec(markDict, commonWordList, 'Mark')
mathVec = createVec(mathDict, commonWordList, 'Mathew')
ignatVec = createVec(ignatDict, commonWordList, 'Ignatius')
testVec = createVec(testDict, commonWordList)

In [18]:
import numpy as np
#testing the vector representations
trainX = np.array((longVec[:len(commonWordList)], markVec[:len(commonWordList)], mathVec[:len(commonWordList)], ignatVec[:len(commonWordList)]))
trainY =['Longus', 'Mark', "Mathew", "Ignatius"]
testX = np.array(testVec[:len(commonWordList)])

In [11]:
#reshaping the vectors
nsamples, nx, ny = trainX.shape
trainXReshape = trainX.reshape((nsamples,nx*ny))

In [12]:
#fitting the MLPClassifier
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(max_iter=8000, hidden_layer_sizes=(4,)).fit(trainXReshape, trainY)

In [13]:
#reshaping test data and printing classifier results
testXReshape = testX.reshape(1,testX.shape[1]*len(commonWordList))
print(clf.classes_)
clf.predict_proba(testXReshape)

['Ignatius' 'Longus' 'Mark' 'Mathew']


array([[0.86731285, 0.09290927, 0.03784939, 0.00192857]], dtype=float32)

In [16]:
#testing KNeighbors
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=4).fit(trainXReshape, trainY)
clf.predict_proba(testX.reshape(1, -1))

array([[0.25, 0.25, 0.25, 0.25]])

In [37]:
#testing SVC
from sklearn.svm import SVC  
clf = SVC(probability=True)
clf.fit(trainXReshape, trainY)
print(clf.classes_)
clf.predict_proba(testX.reshape(1, -1))

['Ignatius' 'Longus' 'Mark' 'Mathew']


array([[0.17953327, 0.27892687, 0.21662632, 0.32491354]])

In [35]:
#testing Logistic Regression
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(trainXReshape, trainY)
print(clf.classes_)
clf.predict_proba(testX.reshape(1, -1))

['Ignatius' 'Longus' 'Mark' 'Mathew']


array([[0.30383462, 0.24570456, 0.25808136, 0.19237946]])

In [36]:
#testing Decision Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
model = DecisionTreeClassifier()
model.fit(trainXReshape, trainY)
print(model.predict_proba(testX.reshape(1, -1)))
print(model.predict(testX.reshape(1,-1)))

[[1. 0. 0. 0.]]
['Ignatius']


In [20]:
#testing LinearSVC
from sklearn.svm import LinearSVC
clf = LinearSVC()
clf.fit(trainXReshape, trainY)
print(clf.classes_)
clf.predict(testX.reshape(1,-1))
#clf.predict_proba(testX.reshape(1, -1))

['Ignatius' 'Longus' 'Mark' 'Mathew']


array(['Ignatius'], dtype='<U8')

In [9]:
import gensim
import numpy as np
from gensim.models import Word2Vec
from sklearn.model_selection import ParameterGrid
from sklearn.neural_network import MLPClassifier

parm_dict = {'min_count':(1,2,4),'alpha':(0.035,0.025,0.015), 'sample':(1.0E-4,1.0E-5,1.0E-6),
             'size':(5, 10, 20, 30, 100, 200), 'sg':(0,1)}
#runs a grid search and prints the results of each iteration
def runGrid():
    param_grid = ParameterGrid(parm_dict)
    for dict_ in param_grid:
        print(dict_)
        import warnings
        warnings.filterwarnings('ignore')
        longModel = Word2Vec(min_count=dict_["min_count"], alpha=dict_["alpha"], sample=dict_["sample"],
                            size=dict_["size"], sg=dict_["sg"]) 
        longModel.build_vocab(long)
        longModel.train(long, total_examples=longModel.corpus_count, epochs=longModel.iter)

        markModel = Word2Vec(min_count=dict_["min_count"], alpha=dict_["alpha"], sample=dict_["sample"],
                            size=dict_["size"], sg=dict_["sg"]) 
        markModel.build_vocab(mark)
        markModel.train(mark, total_examples=markModel.corpus_count, epochs=markModel.iter)

        mathModel = Word2Vec(min_count=dict_["min_count"], alpha=dict_["alpha"], sample=dict_["sample"],
                            size=dict_["size"], sg=dict_["sg"]) 
        mathModel.build_vocab(math)
        mathModel.train(math, total_examples=mathModel.corpus_count, epochs=mathModel.iter)

        ignatModel = Word2Vec(min_count=dict_["min_count"], alpha=dict_["alpha"], sample=dict_["sample"],
                            size=dict_["size"], sg=dict_["sg"]) 
        ignatModel.build_vocab(ignat)
        ignatModel.train(ignat, total_examples=ignatModel.corpus_count, epochs=ignatModel.iter)

        testModel = Word2Vec(min_count=dict_["min_count"], alpha=dict_["alpha"], sample=dict_["sample"],
                            size=dict_["size"], sg=dict_["sg"]) 
        testModel.build_vocab(test)
        testModel.train(test, total_examples=testModel.corpus_count, epochs=testModel.iter)
        
        #creating feature vectors of the models
        longDict = intoDict(longModel)
        markDict = intoDict(markModel)
        mathDict = intoDict(mathModel)
        ignatDict = intoDict(ignatModel)
        testDict = intoDict(testModel)
        #creating vectors to represent the models based on the commonWordList
        commonWordList = ['πάντα', 'αὐτοῦ', 'ἐστιν', 'με', 'αὐτὸν', 'αὐτῶν', 'τοῦτο', 'ἵνα']
        longVec = createVec(longDict, commonWordList, 'Longus')
        markVec = createVec(markDict, commonWordList, 'Mark')
        mathVec = createVec(mathDict, commonWordList, 'Mathew')
        ignatVec = createVec(ignatDict, commonWordList, 'Ignatius')
        testVec = createVec(testDict, commonWordList)

        trainX = np.array((longVec[:5], markVec[:5], mathVec[:5], ignatVec[:5]))
        trainY =["Longus", "Mark", "Mathew", "Ignatius"]
        testX = np.array(testVec[:5])
        nsamples, nx, ny = trainX.shape
        trainXReshape = trainX.reshape((nsamples,nx*ny))

        clf = MLPClassifier(random_state=1, max_iter=2000, hidden_layer_sizes=(4,)).fit(trainXReshape, trainY)
        testXReshape = testX.reshape(1,testX.shape[1]*5)
        print(clf.predict_proba(testXReshape))

In [10]:
#Best results:
#{'alpha': 0.025, 'min_count': 1, 'sample': 0.0001, 'sg': 1, 'size': 5}
#[[0.9479764  0.02267098 0.01563544 0.01371724]]

runGrid()

{'alpha': 0.035, 'min_count': 1, 'sample': 0.0001, 'sg': 0, 'size': 5}
[[0.35799134 0.25402027 0.14626713 0.24172126]]
{'alpha': 0.035, 'min_count': 1, 'sample': 0.0001, 'sg': 0, 'size': 10}
[[0.78810704 0.10900237 0.08427197 0.01861854]]
{'alpha': 0.035, 'min_count': 1, 'sample': 0.0001, 'sg': 0, 'size': 20}
[[0.6793728  0.09022025 0.21664986 0.01375706]]
{'alpha': 0.035, 'min_count': 1, 'sample': 0.0001, 'sg': 0, 'size': 30}
[[0.3954123  0.11974552 0.4235509  0.06129126]]
{'alpha': 0.035, 'min_count': 1, 'sample': 0.0001, 'sg': 0, 'size': 100}
[[0.70495987 0.1797718  0.08754234 0.02772603]]
{'alpha': 0.035, 'min_count': 1, 'sample': 0.0001, 'sg': 0, 'size': 200}
[[0.3394759  0.30070037 0.33721882 0.02260489]]
{'alpha': 0.035, 'min_count': 1, 'sample': 0.0001, 'sg': 1, 'size': 5}
[[0.836386   0.04584666 0.07486286 0.04290443]]
{'alpha': 0.035, 'min_count': 1, 'sample': 0.0001, 'sg': 1, 'size': 10}
[[0.7341607  0.07300888 0.06858843 0.1242419 ]]
{'alpha': 0.035, 'min_count': 1, 'sample

[[0.2678931  0.25142443 0.22953565 0.25114682]]
{'alpha': 0.035, 'min_count': 2, 'sample': 1e-06, 'sg': 1, 'size': 30}
[[0.2028561  0.30815357 0.21604308 0.27294722]]
{'alpha': 0.035, 'min_count': 2, 'sample': 1e-06, 'sg': 1, 'size': 100}
[[0.26372507 0.21190526 0.25680995 0.26755977]]
{'alpha': 0.035, 'min_count': 2, 'sample': 1e-06, 'sg': 1, 'size': 200}
[[0.25362572 0.21198633 0.25602502 0.278363  ]]
{'alpha': 0.035, 'min_count': 4, 'sample': 0.0001, 'sg': 0, 'size': 5}
[[0.42123953 0.20360631 0.32288906 0.05226503]]
{'alpha': 0.035, 'min_count': 4, 'sample': 0.0001, 'sg': 0, 'size': 10}
[[0.58185965 0.03630583 0.36179292 0.02004164]]
{'alpha': 0.035, 'min_count': 4, 'sample': 0.0001, 'sg': 0, 'size': 20}
[[0.5734029  0.00671785 0.3887542  0.03112499]]
{'alpha': 0.035, 'min_count': 4, 'sample': 0.0001, 'sg': 0, 'size': 30}
[[0.42503017 0.10176335 0.4306897  0.04251679]]
{'alpha': 0.035, 'min_count': 4, 'sample': 0.0001, 'sg': 0, 'size': 100}
[[0.680844   0.02524107 0.28297    0.0109

[[0.25362432 0.21198685 0.25602594 0.27836287]]
{'alpha': 0.025, 'min_count': 1, 'sample': 1e-06, 'sg': 1, 'size': 5}
[[0.24505506 0.24799185 0.21500215 0.2919509 ]]
{'alpha': 0.025, 'min_count': 1, 'sample': 1e-06, 'sg': 1, 'size': 10}
[[0.20375936 0.2513679  0.2615401  0.28333262]]
{'alpha': 0.025, 'min_count': 1, 'sample': 1e-06, 'sg': 1, 'size': 20}
[[0.26789892 0.25141957 0.22953846 0.25114307]]
{'alpha': 0.025, 'min_count': 1, 'sample': 1e-06, 'sg': 1, 'size': 30}
[[0.20299649 0.30798674 0.2161753  0.27284148]]
{'alpha': 0.025, 'min_count': 1, 'sample': 1e-06, 'sg': 1, 'size': 100}
[[0.26372433 0.21190606 0.25681016 0.26755944]]
{'alpha': 0.025, 'min_count': 1, 'sample': 1e-06, 'sg': 1, 'size': 200}
[[0.2536127  0.21198483 0.2560381  0.27836436]]
{'alpha': 0.025, 'min_count': 2, 'sample': 0.0001, 'sg': 0, 'size': 5}
[[0.24470645 0.24692234 0.22017966 0.28819156]]
{'alpha': 0.025, 'min_count': 2, 'sample': 0.0001, 'sg': 0, 'size': 10}
[[0.47120076 0.17005336 0.28258348 0.07616238]

[[0.26788852 0.25142574 0.22953157 0.25115418]]
{'alpha': 0.025, 'min_count': 4, 'sample': 1e-06, 'sg': 0, 'size': 30}
[[0.20299648 0.30798668 0.2161753  0.2728415 ]]
{'alpha': 0.025, 'min_count': 4, 'sample': 1e-06, 'sg': 0, 'size': 100}
[[0.26372507 0.21190533 0.25680932 0.2675603 ]]
{'alpha': 0.025, 'min_count': 4, 'sample': 1e-06, 'sg': 0, 'size': 200}
[[0.25362417 0.21198905 0.25602087 0.27836588]]
{'alpha': 0.025, 'min_count': 4, 'sample': 1e-06, 'sg': 1, 'size': 5}
[[0.24502596 0.24797837 0.21502592 0.29196978]]
{'alpha': 0.025, 'min_count': 4, 'sample': 1e-06, 'sg': 1, 'size': 10}
[[0.20374185 0.25141686 0.26147607 0.2833652 ]]
{'alpha': 0.025, 'min_count': 4, 'sample': 1e-06, 'sg': 1, 'size': 20}
[[0.26789126 0.25142547 0.22953327 0.25114995]]
{'alpha': 0.025, 'min_count': 4, 'sample': 1e-06, 'sg': 1, 'size': 30}
[[0.20299645 0.30798674 0.2161753  0.27284148]]
{'alpha': 0.025, 'min_count': 4, 'sample': 1e-06, 'sg': 1, 'size': 100}
[[0.26372486 0.21190552 0.2568099  0.2675597 ]

[[0.2536118  0.21199559 0.2560094  0.2783832 ]]
{'alpha': 0.015, 'min_count': 2, 'sample': 1e-06, 'sg': 0, 'size': 5}
[[0.24502613 0.24797735 0.21502648 0.2919701 ]]
{'alpha': 0.015, 'min_count': 2, 'sample': 1e-06, 'sg': 0, 'size': 10}
[[0.20373537 0.251425   0.26147383 0.28336585]]
{'alpha': 0.015, 'min_count': 2, 'sample': 1e-06, 'sg': 0, 'size': 20}
[[0.26789    0.25142542 0.22953206 0.25115255]]
{'alpha': 0.015, 'min_count': 2, 'sample': 1e-06, 'sg': 0, 'size': 30}
[[0.20285602 0.30815378 0.21604311 0.2729471 ]]
{'alpha': 0.015, 'min_count': 2, 'sample': 1e-06, 'sg': 0, 'size': 100}
[[0.26372477 0.2119055  0.25681    0.26755974]]
{'alpha': 0.015, 'min_count': 2, 'sample': 1e-06, 'sg': 0, 'size': 200}
[[0.25362486 0.21198933 0.25602117 0.27836463]]
{'alpha': 0.015, 'min_count': 2, 'sample': 1e-06, 'sg': 1, 'size': 5}
[[0.24502562 0.24798056 0.21502648 0.2919673 ]]
{'alpha': 0.015, 'min_count': 2, 'sample': 1e-06, 'sg': 1, 'size': 10}
[[0.2037414  0.25141537 0.261476   0.28336725]]


In [4]:
#Ancient greek tagginf the texts
from angel import tag
longTags = tag(longFreq)
markTags = tag(markFreq)
mathTags = tag(mathFreq)
ignatTags = tag(ignatFreq)
testTags = tag(testFreq)

Loading models...
Part-of-speech models loading...
Person models loading...
Number models loading...
Tense models loading...
Mood models loading...
Voice models loading...
Gender models loading...
Case models loading...
Degree models loading...
Pre-processing text...
Text and punctuation split into 15901 individual tokens.
Angel's looking at each word by itself...
Reconsidering tags...
Studying each word in light of its context...
Loading models...
Part-of-speech models loading...
Person models loading...
Number models loading...
Tense models loading...
Mood models loading...
Voice models loading...
Gender models loading...
Case models loading...
Degree models loading...
Pre-processing text...
Text and punctuation split into 9366 individual tokens.
Angel's looking at each word by itself...
Reconsidering tags...
Studying each word in light of its context...
Loading models...
Part-of-speech models loading...
Person models loading...
Number models loading...
Tense models loading...
Mood m

In [5]:
#takes in a tag list and transforms it to 3D vector format
def prepareForW2V(tagList):
    cleaned = [[]]
    line = []
    for word in tagList:
        if (word[0] == "."):
            cleaned.append(line)
            line = []
        else:
            line.append(word[1])
    return cleaned

In [6]:
#transforms the texts into vector format
longPrep = prepareForW2V(longTags)
markPrep = prepareForW2V(mathTags)
mathPrep = prepareForW2V(markTags)
ignatPrep = prepareForW2V(ignatTags)
testPrep = prepareForW2V(testTags)

In [9]:
#returns tags found in all the texts
def getSimTags():
    simWords = []
    for word in testPrep:
        if (word in longPrep and word in markPrep and word in mathPrep and word in ignatPrep):
            simWords.append(word)
    return simWords

In [10]:
#transforms lst to list format
def convertToList(lst):
    ls = []
    for sentence in lst:
        for word in sentence:
            ls.append(word)
    return ls

In [20]:
#creating dictionaries of the models
longDict = intoDict(longModel)
markDict = intoDict(markModel)
mathDict = intoDict(mathModel)
ignatDict = intoDict(ignatModel)
testDict = intoDict(testModel)


commonWordList = getAllSimWords()
#commonWordList = ['n-s---mg-', 'd--------', 'c--------', 'n-s---fd-', 'n-s---fa-', 'v3spia---', 'n-s---mn-', 'n-s---ma-']
#commonWordList = ['n-s---mg-', 'd--------', 'c--------', 'n-s---fd-', 'n-s---fa-', 'v3spia---', 'n-s---mn-', 'n-s---ma-',
#                  'n-s---fg-', 'r--------', 'a-s---mn-']
#commonWordList = ['n-s---mg-', 'd--------', 'c--------', 'n-s---fd-', 'n-s---fa-', 'v3spia---', 'n-s---mn-', 'n-s---ma-',
#                  'n-s---fg-', 'r--------', 'a-s---mn-', 'n-s---fn-', 'n-s---md-', 'v--pna---', 'p-s---mg-', 'a-p---mn-',
#                  'v--ana---', 'n-s---na-', 'p-s---na-', 'v1spia---', 'n-s---nd-']
#commonWordList = ['n', 'v', 'p', 'a', 'd', 'c', 'r', 'l']

#creating vectors to represent the models based on the commonWordList
longVec = createVec(longDict, commonWordList, 'Longus')
markVec = createVec(markDict, commonWordList, 'Mark')
mathVec = createVec(mathDict, commonWordList, 'Mathew')
ignatVec = createVec(ignatDict, commonWordList, 'Ignatius')
testVec = createVec(testDict, commonWordList)

In [21]:
#training the model for POS tag
import numpy as np
trainX = np.array((longVec[:len(commonWordList)], markVec[:len(commonWordList)], mathVec[:len(commonWordList)], ignatVec[:len(commonWordList)]))
trainY =['Longus', 'Mark', "Mathew", "Ignatius"]
testX = np.array(testVec[:len(commonWordList)])

In [18]:
#returns results of Ignatius n (iterations) times.
def runIteration(iterations):
    av = 0
    for i in range(0, iterations):
        nsamples, nx, ny = trainX.shape
        trainXReshape = trainX.reshape((nsamples,nx*ny))
        from sklearn.neural_network import MLPClassifier
        clf = MLPClassifier(max_iter=8000, hidden_layer_sizes=(4,)).fit(trainXReshape, trainY)
        testXReshape = testX.reshape(1,testX.shape[1]*len(commonWordList))
        av += clf.predict_proba(testXReshape)[0][0]
    print("Average: ", av/iterations)

In [131]:
#Common word list of all similar items (pos tag)
runIteration(100)

Average:  0.8834028397500515


In [19]:
#Common word list of 8 most similar items (pos tag)
runIteration(100)

Average:  0.8538072580099105


In [22]:
#Common word list of 21 most similar items (pos tag)
runIteration(100)

Average:  0.8277810156345368


In [174]:
#Common words list of all similar items (n, v, etc tags)
runIteration(100)

Average:  0.8649469165503979


In [179]:
#Common words list of only important tags (n, v, etc tags)
runIteration(100)

Average:  0.8735872340202332
